# Generated by Django 5.2.3 on 2025-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('encrypt', 'Encryption'), ('decrypt', 'Decryption')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encryption_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OTPKeyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('aes_key', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_key_mappings',
                'ordering': ['-created_at'],
            },
        ),
    ]
